const state={theme:localStorage.theme||'light',grade:localStorage.grade||'9',xp:+localStorage.xp||0,solved:+localStorage.solved||0,correct:+localStorage.correct||0,streak:+localStorage.streak||0,current:null,chapter:null,game:null};
const base=[['➕','Tal & räkning','Addition, subtraktion, multiplikation och division','E–C'],['🔢','Bråk','Förkorta, förlänga, jämföra och räkna med bråk','E–A'],['📊','Procent','Procent, förändring, rabatt och ökning','E–A'],['📐','Geometri','Area, omkrets, volym, vinklar och Pythagoras','E–A'],['📈','Statistik','Medelvärde, median, typvärde och diagram','E–A'],['✖️','Algebra','Uttryck, förenkling och algebraiska regler','E–A'],['🧩','Ekvationer','Lös ekvationer och olikheter','E–A'],['²','Potenser','Potenser, potenslagar och tiopotenser','C–A'],['√','Rötter','Kvadratrötter och samband','C–A'],['📏','Enheter','Längd, area, volym, massa och tid','E–C'],['💰','Ekonomi','Pengar, ränta, lön och budget','E–A'],['📈','Funktioner','Koordinater, grafer och linjära funktioner','C–A']];
const gym=[['∑','Matematik 1 – Algebra','Uttryck, ekvationer och algebraiska metoder','E–A'],['📈','Matematik 1 – Funktioner','Linjära funktioner, grafer och modeller','E–A'],['📐','Matematik 1 – Geometri','Geometriska samband och trigonometri','E–A'],['📊','Matematik 1 – Statistik','Statistiska mått, diagram och spridning','E–A'],['🎲','Matematik 1 – Sannolikhet','Sannolikhetsmodeller och kombinatorik','C–A'],['∫','Matematik 2 – Algebra','Andragradsekvationer och algebraiska metoder','C–A'],['📈','Matematik 2 – Exponentialfunktioner','Exponentialekvationer och modeller','C–A'],['📐','Matematik 2 – Trigonometri','Sinus, cosinus och trigonometriska samband','C–A'],['🧮','Matematik 3 – Derivata','Gränsvärden och derivatans användning','C–A'],['∫','Matematik 3 – Integraler','Primitiva funktioner och integraler','C–A'],['🌀','Matematik 3 – Trigonometri','Trigonometriska funktioner och identiteter','C–A'],['🔬','Matematik 4 – Komplexa tal','Komplexa tal och polär form','A'],['∑','Matematik 4 – Vektorer','Vektorer och analytisk geometri','C–A'],['📉','Matematik 4 – Differentialekvationer','Enkla differentialekvationer och modeller','A'],['🧠','Matematik 5 – Diskret matematik','Induktion, rekursion och kombinatorik','A'],['∑','Matematik 5 – Differentialekvationer','Fördjupade differentialekvationer','A']];
const themes=['Taluppfattning','Huvudräkning','Problemlösning','Mönster','Logik','Rimlighet','Matematiska modeller','Mental matte','Blandade tal','Repetition'];
const levels=['E','D','C','B','A'];
const chapters=[...base,...gym,...themes.flatMap((t,j)=>base.slice(0,10).map((c,i)=>[c[0],`${t}: ${c[1]}`,`${c[2]} – nivå ${levels[(i+j)%5]}`,levels[(i+j)%5]])),...Array.from({length:120},(_,i)=>['🧠',`Utmaning ${i+1}`,`Slumpade blandade uppgifter och problemlösning`,levels[i%5]])];
const $=s=>document.querySelector(s);const save=()=>Object.entries(state).forEach(([k,v])=>{if(['theme','grade','xp','solved','correct','streak'].includes(k))localStorage[k]=v});
function shell(v){document.body.dataset.theme=state.theme==='dark'?'dark':'';document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand"><div class="logo">M</div>MatteSkolan</div><div class="top-actions"><button class="icon-btn" onclick="toggleTheme()">${state.theme==='dark'?'☀️':'🌙'}</button><button class="profile">👤 Elev</button></div></header><div class="layout"><aside class="side"><button class="nav ${v==='home'?'active':''}" onclick="home()">🏠 Översikt</button><button class="nav ${v==='chapters'?'active':''}" onclick="showChapters()">📚 Kapitel</button><button class="nav ${v==='practice'?'active':''}" onclick="startRandom()">🎯 Träna</button><button class="nav ${v==='games'?'active':''}" onclick="games()">🎮 Mattespel</button><button class="nav ${v==='stats'?'active':''}" onclick="stats()">📊 Statistik</button><button class="nav ${v==='settings'?'active':''}" onclick="settings()">⚙️ Inställningar</button></aside><main class="main" id="main"></main></div><div id="toast" class="toast"></div></div>`}
function home(){shell('home');$('#main').innerHTML=`<section class="hero"><div><h1>Välkommen till MatteSkolan 👋</h1><p>Hundratals kapitel. Nästan obegränsat med nya uppgifter.</p></div><div class="hero-badge"><small>Nivå</small><strong style="font-size:30px;display:block">${state.grade==='gym'?'Gymnasiet':'Åk '+state.grade}</strong></div></section><div class="grid"><div class="card stat"><span class="muted">XP</span><b>${state.xp}</b><div class="progress"><span style="width:${state.xp%100}%"></span></div></div><div class="card stat"><span class="muted">Lösta</span><b>${state.solved}</b><span class="muted">${state.correct} rätt</span></div><div class="card stat"><span class="muted">Streak</span><b>🔥 ${state.streak}</b><span class="muted">i rad</span></div></div><div class="section-title"><h2>Fortsätt träna</h2><button class="primary" onclick="startRandom()">Starta uppgift →</button></div><div class="chapters">${chapters.slice(0,9).map((c,i)=>chapterCard(c,i)).join('')}</div>`}
function chapterCard(c,i){return `<button class="chapter" onclick="startChapter(${i})"><span class="emoji">${c[0]}</span><h3>${c[1]}</h3><p class="muted">${c[2]}</p><span class="tag">${c[3]}</span></button>`}
function showChapters(){shell('chapters');$('#main').innerHTML=`<div class="section-title"><div><h1>Alla kapitel</h1><p class="muted">${chapters.length}+ kategorier och dynamiska variationer.</p></div><select onchange="state.grade=this.value;save();showChapters()"><option value="1" ${state.grade==='1'?'selected':''}>Åk 1</option><option value="4" ${state.grade==='4'?'selected':''}>Åk 4</option><option value="7" ${state.grade==='7'?'selected':''}>Åk 7</option><option value="9" ${state.grade==='9'?'selected':''}>Åk 9</option><option value="gym" ${state.grade==='gym'?'selected':''}>Gymnasiet</option></select></div><div class="chapters">${chapters.map((c,i)=>chapterCard(c,i)).join('')}</div>`}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}function pick(a){return a[rand(0,a.length-1)]}function gcd(a,b){while(b){[a,b]=[b,a%b]}return Math.abs(a)}function clean(n){return Math.round(n*100)/100}
function generate(type){const gymMode=state.grade==='gym',d=gymMode?5:Math.min(5,Math.ceil(+state.grade/2));let a,b,ans,q,hint;const mode=type%12;if(gymMode&&type%5===0){a=rand(2,10);b=rand(1,12);ans=clean((b/a));q=`Lös: ${a}x = ${b}`;hint=`Mål: få x ensamt. Vilken operation tar bort faktorn ${a}?`;return{q,ans,hint}}
if(mode===0){a=rand(2,25*d);b=rand(2,25*d);let op=pick(['+','−','×','÷']);if(op==='÷'){b=rand(2,12*d);a=b*rand(2,12*d);ans=a/b}else ans=op==='+'?a+b:op==='−'?a-b:a*b;q=`${a} ${op} ${b} = ?`;hint=op==='−'?'Börja med entalen och tänk på om du behöver växla.':op==='×'?'Dela upp multiplikationen i enklare delar.':'Räkna lugnt från vänster till höger.'}
if(mode===1){b=rand(3,15);a=rand(1,b-1);let b2=rand(3,15),a2=rand(1,b2-1);let g=gcd(a,b),g2=gcd(a2,b2);a/=g;b/=g;a2/=g2;b2/=g2;ans=clean(a/b+a2/b2);q=`${a}/${b} + ${a2}/${b2} = ?`;hint='Hitta en gemensam nämnare. Förläng bråken så att nämnarna blir lika.'}
if(mode===2){let price=rand(100,3000),p=pick([10,15,20,25,30,40]);ans=price*(1-p/100);q=`En vara kostar ${price} kr och får ${p}% rabatt. Pris efter rabatt?`;hint=`Efter en rabatt på ${p}% återstår ${100-p}%. Räkna den delen av priset.`}
if(mode===3){let l=rand(3,18*d),w=rand(2,15*d);ans=l*w;q=`En rektangel är ${l} cm × ${w} cm. Area?`;hint='Area för rektangel = längd · bredd. Skriv formeln först.'}
if(mode===4){a=rand(10,100);b=rand(10,100);let c=rand(10,100);ans=clean((a+b+c)/3);q=`Medelvärdet av ${a}, ${b} och ${c}?`;hint='Addera alla tre tal. Dela sedan summan med 3.'}
if(mode===5){a=rand(2,12);b=rand(2,20);ans=a+b;q=`Förenkla uttrycket: ${a}x + ${b}x`;hint='Båda termerna har x. Addera deras koefficienter och behåll x.'}
if(mode===6){a=rand(2,12);b=rand(2,30);ans=clean(b/a);q=`Lös ekvationen: ${a}x = ${b}`;hint=`Du vill få x ensamt. Dela båda leden med ${a}.`}
if(mode===7){a=rand(2,12);let n=rand(2,4);ans=Math.pow(a,n);q=`${a}^${n} = ?`;hint=`${n} betyder att ${a} multipliceras med sig själv ${n} gånger.`}
if(mode===8){a=rand(2,15);ans=a;q=`√${a*a} = ?`;hint=`Sök talet som multiplicerat med sig självt blir ${a*a}.`}
if(mode===9){a=rand(2,30);ans=a*100;q=`${a} m = ? cm`;hint='Från meter till centimeter: multiplicera med 100.'}
if(mode===10){a=rand(100,2000);b=rand(5,30);ans=a+b;q=`Du har ${a} kr och får ${b} kr. Hur mycket har du?`;hint='Det här är en addition: lägg ihop de två beloppen.'}
if(mode===11){a=rand(1,10);b=rand(1,8);ans=a+b;q=`f(x)=x+${a}. Vad är f(${b})?`;hint=`Byt ut x mot ${b}. Räkna sedan uttrycket.`}
return{q,ans:clean(ans),hint}}
function startChapter(i){state.chapter=i;practice()}function startRandom(){state.chapter=null;practice()}function practice(){shell('practice');nextProblem()}
function nextProblem(){const i=state.chapter===null?rand(0,chapters.length-1):state.chapter;state.current=generate(i);$('#main').innerHTML=`<div class="lesson"><div class="section-title"><div><span class="tag">${chapters[i][1]}</span><h1>Ny uppgift</h1></div><span class="muted">${state.solved+1} lösta</span></div><div class="problem-card"><p class="muted">${state.grade==='gym'?'Gymnasienivå':'Årskurs '+state.grade}</p><div class="question">${state.current.q}</div><input id="answer" class="answer" inputmode="decimal" autocomplete="off" placeholder="Skriv ditt svar"><div class="actions"><button class="primary" onclick="check()">Kontrollera</button><button class="secondary" onclick="hint()">💡 Ledtråd</button><button class="secondary" onclick="nextProblem()">Nästa →</button></div><div id="feedback" class="feedback"></div></div></div>`;$('#answer').focus();$('#answer').addEventListener('keydown',e=>{if(e.key==='Enter')check()})}
function check(){const el=$('#answer'),got=Number(el.value.replace(',','.').trim()),ok=Number.isFinite(got)&&Math.abs(got-state.current.ans)<.011;state.solved++;if(ok){state.correct++;state.streak++;state.xp+=10;$('#feedback').innerHTML='<span class="good">✓ Rätt! +10 XP</span>';toast('Snyggt! 🎉')}else{state.streak=0;$('#feedback').innerHTML='<span class="bad">✕ Inte riktigt — försök igen.</span>';el.value='';el.focus();el.animate([{transform:'translateX(-7px)'},{transform:'translateX(7px)'},{transform:'translateX(0)'}],{duration:250});}save()}
function hint(){const f=$('#feedback');f.innerHTML=`<div class="hint">💡 <b>Ledtråd</b><br>${state.current.hint}</div>`}function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)}
function games(){shell('games');$('#main').innerHTML=`<h1>🎮 Mattespel</h1><p class="muted">Träna matte utan att det känns som vanlig träning.</p><div class="game-grid"><div class="game"><div class="game-icon">⚡</div><h2>Snabbmatte</h2><p class="muted">Lös så många du kan på 60 sekunder.</p><button class="primary" onclick="speedGame()">Spela</button></div><div class="game"><div class="game-icon">🧠</div><h2>Taljägaren</h2><p class="muted">Hitta rätt tal bland luriga alternativ.</p><button class="primary" onclick="targetGame()">Spela</button></div><div class="game"><div class="game-icon">🏆</div><h2>Streak Rush</h2><p class="muted">Bygg en så lång korrekt svit som möjligt.</p><button class="primary" onclick="startRandom()">Spela</button></div></div>`}
function speedGame(){shell('games');let score=0,time=30,timer;function round(){const a=rand(2,20),b=rand(2,20),op=pick(['+','−','×']),ans=op==='+'?a+b:op==='−'?a-b:a*b;$('#main').innerHTML=`<div class="problem-card"><span class="tag">⚡ ${time}s</span><h1>Snabbmatte</h1><div class="question">${a} ${op} ${b}</div><input id="gameAns" class="answer" inputmode="numeric" autofocus><div class="actions"><button class="primary" onclick="gcheck(${ans})">Svara</button></div><h2>Poäng: ${score}</h2></div>`;$('#gameAns').addEventListener('keydown',e=>{if(e.key==='Enter')gcheck(ans)})}window.gcheck=n=>{if(Number($('#gameAns').value)===n)score++;round()};round();timer=setInterval(()=>{time--;if(time<=0){clearInterval(timer);$('#main').innerHTML=`<div class="problem-card"><h1>🏁 Tiden är slut!</h1><div class="question">${score} poäng</div><button class="primary" onclick="games()">Spela igen</button></div>`}else round()},1000)}
function targetGame(){shell('games');const n=rand(20,99),opts=[n,n+rand(1,8),n-rand(1,8),n+rand(10,20)].sort(()=>Math.random()-.5);$('#main').innerHTML=`<div class="problem-card"><span class="tag">🧠 Taljägaren</span><h1>Vilket tal saknas?</h1><div class="question">${n-2}, ${n-1}, ?, ${n+1}, ${n+2}</div><div class="actions">${opts.map(x=>`<button class="primary" onclick="${x===n?`toast('Rätt! 🎉');setTimeout(targetGame,500)`:`toast('Inte riktigt! Försök igen.')`}">${x}</button>`).join('')}</div></div>`}
function stats(){shell('stats');const pct=state.solved?Math.round(state.correct/state.solved*100):0;$('#main').innerHTML=`<h1>Din statistik</h1><p class="muted">Din utveckling sparas lokalt i webbläsaren.</p><div class="grid"><div class="card stat"><span class="muted">XP</span><b>${state.xp}</b></div><div class="card stat"><span class="muted">Uppgifter</span><b>${state.solved}</b></div><div class="card stat"><span class="muted">Träffsäkerhet</span><b>${pct}%</b></div></div><div class="card" style="margin-top:20px"><h2>Nivå ${Math.floor(state.xp/100)+1}</h2><div class="progress"><span style="width:${state.xp%100}%"></span></div><p class="muted">${100-state.xp%100} XP till nästa nivå.</p></div>`}
function settings(){shell('settings');$('#main').innerHTML=`<h1>Inställningar</h1><div class="card"><div class="settings-row"><div><b>Studienivå</b><div class="muted">Styr svårighet och kategorier.</div></div><select onchange="state.grade=this.value;save();settings()"><option value="1" ${state.grade==='1'?'selected':''}>Åk 1</option><option value="4" ${state.grade==='4'?'selected':''}>Åk 4</option><option value="7" ${state.grade==='7'?'selected':''}>Åk 7</option><option value="9" ${state.grade==='9'?'selected':''}>Åk 9</option><option value="gym" ${state.grade==='gym'?'selected':''}>Gymnasiet</option></select></div><div class="settings-row"><div><b>Tema</b><div class="muted">Ljust eller mörkt.</div></div><button class="secondary" onclick="toggleTheme()">${state.theme==='dark'?'☀️ Ljust':'🌙 Mörkt'}</button></div><div class="settings-row"><div><b>Återställ statistik</b></div><button class="secondary" onclick="resetData()">Återställ</button></div></div>`}
function resetData(){if(confirm('Återställa all lokal statistik?')){state.xp=state.solved=state.correct=state.streak=0;save();stats()}}function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';save();document.body.dataset.theme=state.theme==='dark'?'dark':'';home()}home();