const state={theme:localStorage.theme||'light',grade:localStorage.grade||'9',xp:+localStorage.xp||0,solved:+localStorage.solved||0,correct:+localStorage.correct||0,streak:+localStorage.streak||0,current:null,chapter:null};
const chapters=[
 ['➕','Tal & räkning','Addition, subtraktion, multiplikation och division','E–C'],['🔢','Bråk','Förkorta, förlänga, jämföra och räkna med bråk','E–A'],['📊','Procent','Procent, förändring, rabatt och ökning','E–A'],['📐','Geometri','Area, omkrets, volym, vinklar och Pythagoras','E–A'],['📈','Statistik','Medelvärde, median, typvärde och diagram','E–A'],['✖️','Algebra','Uttryck, förenkling och algebraiska regler','E–A'],['🧩','Ekvationer','Lös enkla och avancerade ekvationer','E–A'],['²','Potenser','Potenser, potenslagar och tiopotenser','C–A'],['√','Rötter','Kvadratrötter och samband','C–A'],['📏','Enheter','Längd, area, volym, massa och tid','E–C'],['💰','Ekonomi','Pengar, ränta, lön och budget','E–A'],['📐','Funktioner','Koordinater, grafer och linjära funktioner','C–A']];
const $=s=>document.querySelector(s); const save=()=>{Object.entries(state).forEach(([k,v])=>{if(['theme','grade','xp','solved','correct','streak'].includes(k))localStorage[k]=v})};
function layout(view='home'){document.body.dataset.theme=state.theme==='dark'?'dark':'';document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand"><div class="logo">M</div>MatteSkolan</div><div class="top-actions"><button class="icon-btn" onclick="toggleTheme()">${state.theme==='dark'?'☀️':'🌙'}</button><button class="profile">👤 Elev</button></div></header><div class="layout"><aside class="side"><button class="nav ${view==='home'?'active':''}" onclick="home()">🏠 Översikt</button><button class="nav ${view==='chapters'?'active':''}" onclick="showChapters()">📚 Kapitel</button><button class="nav ${view==='practice'?'active':''}" onclick="startRandom()">🎯 Träna</button><button class="nav ${view==='stats'?'active':''}" onclick="stats()">📊 Statistik</button><button class="nav ${view==='settings'?'active':''}" onclick="settings()">⚙️ Inställningar</button></aside><main class="main" id="main"></main></div><div id="toast" class="toast"></div></div>`; if(view==='home')home();}
function home(){layoutBase('home');$('#main').innerHTML=`<section class="hero"><div><h1>Välkommen till MatteSkolan 👋</h1><p>Träna matte på din nivå och bygg din kunskap steg för steg.</p></div><div class="hero-badge"><small>Årskurs</small><strong style="font-size:30px;display:block">${state.grade}</strong></div></section><div class="grid"><div class="card stat"><span class="muted">XP</span><b>${state.xp}</b><div class="progress"><span style="width:${Math.min(100,state.xp%100)}%"></span></div></div><div class="card stat"><span class="muted">Lösta uppgifter</span><b>${state.solved}</b><span class="muted">${state.correct} rätt</span></div><div class="card stat"><span class="muted">Streak</span><b>🔥 ${state.streak}</b><span class="muted">i rad</span></div></div><div class="section-title"><h2>Fortsätt träna</h2><button class="primary" onclick="startRandom()">Starta uppgift</button></div><div class="chapters">${chapters.slice(0,6).map((c,i)=>chapterCard(c,i)).join('')}</div>`}
function layoutBase(v){document.body.dataset.theme=state.theme==='dark'?'dark':'';document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand"><div class="logo">M</div>MatteSkolan</div><div class="top-actions"><button class="icon-btn" onclick="toggleTheme()">${state.theme==='dark'?'☀️':'🌙'}</button><button class="profile">👤 Elev</button></div></header><div class="layout"><aside class="side"><button class="nav ${v==='home'?'active':''}" onclick="home()">🏠 Översikt</button><button class="nav ${v==='chapters'?'active':''}" onclick="showChapters()">📚 Kapitel</button><button class="nav ${v==='practice'?'active':''}" onclick="startRandom()">🎯 Träna</button><button class="nav ${v==='stats'?'active':''}" onclick="stats()">📊 Statistik</button><button class="nav ${v==='settings'?'active':''}" onclick="settings()">⚙️ Inställningar</button></aside><main class="main" id="main"></main></div><div id="toast" class="toast"></div></div>`}
function chapterCard(c,i){return `<button class="chapter" onclick="startChapter(${i})"><span class="emoji">${c[0]}</span><h3>${c[1]}</h3><p class="muted">${c[2]}</p><span class="tag">${c[3]}</span></button>`}
function showChapters(){layoutBase('chapters');$('#main').innerHTML=`<div class="section-title"><div><h1>Alla kapitel</h1><p class="muted">Varje kapitel kan generera miljontals unika uppgifter.</p></div><select onchange="state.grade=this.value;save();showChapters()"><option ${state.grade==='1'?'selected':''}>1</option><option ${state.grade==='4'?'selected':''}>4</option><option ${state.grade==='7'?'selected':''}>7</option><option ${state.grade==='9'?'selected':''}>9</option><option ${state.grade==='gym'?'selected':''} value="gym">Gymnasiet</option></select></div><div class="chapters">${chapters.map((c,i)=>chapterCard(c,i)).join('')}</div>`}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a} function pick(a){return a[rand(0,a.length-1)]} function gcd(a,b){while(b){[a,b]=[b,a%b]}return Math.abs(a)}
function generate(type){const d=state.grade==='gym'?4:Math.min(4,Math.ceil(+state.grade/3));let a,b,n,ans,q,hint;if(type===0){a=rand(2,20*d+20);b=rand(2,20*d+20);const op=pick(['+','−','×','÷']);if(op==='÷'){b=rand(2,12*d);a=b*rand(2,12*d);ans=a/b}else{ans=op==='+'?a+b:op==='−'?a-b:a*b}q=`${a} ${op} ${b} = ?`;hint='Räkna ett steg i taget och kontrollera tecknet.'}
if(type===1){a=rand(1,9*d);b=rand(2,12*d);let c=rand(1,b-1);let g=gcd(c,b);c/=g;b/=g;let c2=rand(1,8*d),b2=rand(2,10*d);let g2=gcd(c2,b2);c2/=g2;b2/=g2;ans=c/b+c2/b2;q=`${c}/${b} + ${c2}/${b2} = ?`;ans=Math.round(ans*100)/100;hint='Hitta gemensam nämnare och förenkla.'}
if(type===2){let price=rand(100,2000);let p=pick([10,15,20,25,30,40]);ans=price*(1-p/100);q=`En vara kostar ${price} kr och får ${p}% rabatt. Vad kostar den?`;hint=`Räkna ${100-p}% av priset.`}
if(type===3){let l=rand(3,15*d),w=rand(2,12*d);ans=l*w;q=`En rektangel är ${l} cm lång och ${w} cm bred. Vad är arean?`;hint='Area = längd × bredd.'}
if(type===4){a=rand(10,100);b=rand(10,100);ans=(a+b)/2;q=`Vad är medelvärdet av ${a}, ${b} och ${a+b}?`;ans=Math.round(ans*100)/100;hint='Addera alla tal och dela med antalet tal.'}
if(type===5){a=rand(2,10*d);b=rand(2,20*d);ans=a+b;q=`Förenkla: ${a}x + ${b} = ?`;hint='Konstanter och x-termer kan inte alltid slås ihop.'}
if(type===6){a=rand(2,12);b=rand(1,30);ans=b/a;q=`Lös ekvationen: ${a}x = ${b}`;ans=Math.round(ans*100)/100;hint=`Dela båda leden med ${a}.`}
if(type===7){a=rand(2,12);n=rand(2,3);ans=Math.pow(a,n);q=`${a}^${n} = ?`;hint='En potens betyder att talet multipliceras med sig självt.'}
if(type===8){a=rand(2,15);ans=Math.sqrt(a*a);q=`√${a*a} = ?`;hint='Vilket tal multiplicerat med sig självt ger talet under roten?'}
if(type===9){a=rand(2,20);ans=a*100;q=`${a} m = ? cm`;hint='1 meter = 100 centimeter.'}
if(type===10){a=rand(100,2000);b=rand(5,20);ans=a+b;q=`Du har ${a} kr och får ${b} kr. Hur mycket har du nu?`;hint='Addera beloppen.'}
if(type===11){a=rand(1,10);b=rand(1,8);ans=a+b;q=`En linjär funktion har f(x)=x+${a}. Vad är f(${b})?`;hint='Sätt in x-värdet i uttrycket.'}
return {q,ans,hint};}
function startChapter(i){state.chapter=i;practice()};function startRandom(){state.chapter=null;practice()};function practice(){layoutBase('practice');nextProblem();}
function nextProblem(){const i=state.chapter===null?rand(0,chapters.length-1):state.chapter;state.current=generate(i);$('#main').innerHTML=`<div class="lesson"><div class="section-title"><div><span class="tag">${chapters[i][1]}</span><h1>Träningsuppgift</h1></div><span class="muted">Uppgift ${state.solved+1}</span></div><div class="problem-card"><p class="muted">Årskurs ${state.grade}</p><div class="question">${state.current.q}</div><input id="answer" class="answer" inputmode="decimal" autocomplete="off" placeholder="Skriv ditt svar"><div class="actions"><button class="primary" onclick="check()">Kontrollera</button><button class="secondary" onclick="hint()">💡 Ledtråd</button><button class="secondary" onclick="nextProblem()">Nästa →</button></div><div id="feedback" class="feedback"></div></div></div>`;$('#answer').focus();$('#answer').addEventListener('keydown',e=>{if(e.key==='Enter')check()})}
function check(){const el=$('#answer'),raw=el.value.replace(',','.').trim(),got=Number(raw),ok=Number.isFinite(got)&&Math.abs(got-state.current.ans)<0.011;state.solved++;if(ok){state.correct++;state.streak++;state.xp+=10;$('#feedback').innerHTML=`<span class="good">✓ Rätt! +10 XP</span>`;toast('Snyggt! 🎉')}else{state.streak=0;$('#feedback').innerHTML=`<span class="bad">✕ Inte riktigt. Rätt svar är ${fmt(state.current.ans)}.</span>`}save();$('#answer').disabled=true}
function fmt(n){return Number.isInteger(n)?n:String(Math.round(n*100)/100).replace('.',',')} function hint(){$('#feedback').innerHTML=`<span class="muted">💡 ${state.current.hint}</span>`} function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)}
function stats(){layoutBase('stats');const pct=state.solved?Math.round(state.correct/state.solved*100):0;$('#main').innerHTML=`<h1>Din statistik</h1><p class="muted">Här ser du din utveckling.</p><div class="grid"><div class="card stat"><span class="muted">XP</span><b>${state.xp}</b></div><div class="card stat"><span class="muted">Uppgifter</span><b>${state.solved}</b></div><div class="card stat"><span class="muted">Rättprocent</span><b>${pct}%</b></div></div><div class="card" style="margin-top:20px"><h2>Din nivå</h2><p>Du är på nivå ${Math.floor(state.xp/100)+1}.</p><div class="progress"><span style="width:${state.xp%100}%"></span></div><p class="muted">${100-state.xp%100} XP till nästa nivå.</p></div>`}
function settings(){layoutBase('settings');$('#main').innerHTML=`<h1>Inställningar</h1><div class="card"><div class="settings-row"><div><b>Årskurs</b><div class="muted">Används för att anpassa uppgifterna.</div></div><select onchange="state.grade=this.value;save()"><option ${state.grade==='1'?'selected':''}>1</option><option ${state.grade==='4'?'selected':''}>4</option><option ${state.grade==='7'?'selected':''}>7</option><option ${state.grade==='9'?'selected':''}>9</option><option ${state.grade==='gym'?'selected':''} value="gym">Gymnasiet</option></select></div><div class="settings-row"><div><b>Tema</b><div class="muted">Växla mellan ljust och mörkt läge.</div></div><button class="secondary" onclick="toggleTheme();settings()">${state.theme==='dark'?'Ljust':'Mörkt'}</button></div><div class="settings-row"><div><b>Återställ statistik</b><div class="muted">Tar bort lokal träningsdata.</div></div><button class="secondary" onclick="resetData()">Återställ</button></div></div>`}
function resetData(){if(confirm('Är du säker?')){state.xp=state.solved=state.correct=state.streak=0;save();stats()}} function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';save();document.body.dataset.theme=state.theme==='dark'?'dark':'';home()}
layout('home');